sudo: required
language: node_js
services:
    - docker
before_install:
    - docker build -t gyuvaraj10/laranerds .

after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" hub.docker.com
    - docker push gyuvaraj10/laranerds:v0.1
    - docker images
 

